# Generated by Django 4.1.3 on 2022-11-23 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ing', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ing', models.CharField(max_length=50)),
                ('descp_ing', models.CharField(max_length=50)),
                ('tipo_ing', models.CharField(max_length=50)),
                ('estado_ing', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nom_plato', models.CharField(max_length=50)),
                ('valor_plato', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('Imagen', models.ImageField(default=None, null=True, upload_to='platos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[['Pendiente Pago', 'Pendiente Pago'], ['Cancelado', 'Cancelado'], ['Confirmado', 'Confirmado'], ['Preparando', 'Preparando'], ['Pagado', 'Pagado'], ['Atrasado', 'Atrasado']], default='Pendiente Pago', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plato')),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'linea pedido',
                'verbose_name_plural': 'lineas pedidos',
                'db_table': 'lineapedidos',
                'ordering': ['id'],
            },
        ),
    ]
