# Generated by Django 4.1.3 on 2022-11-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mesas_producto_proveedor_delete_ingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_min',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
