# Generated by Django 4.1.3 on 2022-11-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto_stock_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[['En Stock', 'En Stock'], ['Stock Bajo', 'Stock Bajo'], ['Stock Critico', 'Stock Critico'], ['Agotado', 'Agotado']], default='Agotado', max_length=50),
        ),
    ]
