# Generated by Django 4.1.3 on 2022-11-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesas',
            name='estadoMesa',
            field=models.CharField(choices=[['Disponible', 'Disponible'], ['Ocupada', 'Ocupada'], ['Pago Pendiente', 'Pago Pendiente'], ['Limpiando', 'Limpiando']], default='Disponible', max_length=50),
        ),
    ]
