# Generated by Django 4.1.3 on 2022-11-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mesas_estadomesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
